Feature/Base Table
Holo-Host/ui-common-library pull request #27
Opened 2022-09-28 12:48 UTC by mateuszRybczonek

This PR adds reusable components for the table:

<img width="1200" alt="Screenshot 2022-09-28 at 14 43 47" src="https://user-images.githubusercontent.com/17565389/192781492-315b4034-e1e7-4abc-95c1-941689595a08.png">

The table handles sorting and pagination internally and exposes an `items` via scoped slot.

For details how to use it please have a look at the `BaseTable.stories.js` and host-console-ui

Page:
https://github.com/Holo-Host/host-console-ui/blob/feature/invoices-table/src/pages/PaidInvoicesPage.vue

Invoices header/item/expandable-content components:
https://github.com/Holo-Host/host-console-ui/tree/feature/invoices-table/src/components/invoices

2022-09-28 20:05 UTC, robbiecarlton requested changes
Overall looks great. Couple of questions and suggestions.

I have a "tabs || spaces" topic for ui/ux guild meeting this week ;>

2022-09-28 20:05 UTC, robbiecarlton commented on package.json
> +    "dayjs": "^1.11.5",
we already have momentjs in this repo. Is there something we can't do with that?

2022-09-28 20:05 UTC, robbiecarlton commented on src/components/BaseCard.vue
> +				:class="`body--margin-${margin}`"
there are mixed tabs and spaces in this file and others.

2022-09-28 20:05 UTC, robbiecarlton commented on src/components/BaseTable.vue
> +	})
we have lodash  in this repo, so you can
`import { orderBy } from 'lodash'` 
and then just do
```suggestion
        const sortDir = sortDesc.value ? 'desc' : 'asc'
        return orderBy(props.items, sortBy.value, sortDir)
```

2022-09-28 20:05 UTC, robbiecarlton commented on src/components/BaseTable.vue
> +	sortDesc.value = direction === 'desc'
If you do
```suggestion
	sortDir.value = direction
```
You can remove line 65 in my suggestion above.

I think this came from the original holofuel ui implementation, and you're just duplicating that here, but I'm not sure why we did it that way.

2022-09-28 20:05 UTC, robbiecarlton commented on src/components/BaseTable.vue
> +	sortDesc.value = direction === 'desc'
alternatively, if you want to keep this patter around, shouldn't it be
```suggestion
	sortDesc.value = direction === ESortDirections.desc
```

2022-09-29 05:39 UTC, mateuszRybczonek commented on package.json
> +    "dayjs": "^1.11.5",
I think we should move away from `momentjs` and `dayjs` seems to be a natuaral replacement. There are few reasons to do that:
- `momentjs` is dead - it is not developed anymore since 2020 the team admits "Moment was built for the previous era of the JavaScript ecosystem. The modern web looks much different these days" and suggests to switch to an alternative.
- size - `momentjs` Gzipped size: 75.58 KB vs. `dayjs` Gzipped size: 2.91 KB
- speed - `dayjs` is at average 4x faster
- both have very similar APIs

For more please check the `momemntjs` docs - https://momentjs.com/docs/#/-project-status/

2022-09-29 05:40 UTC, mateuszRybczonek commented on src/components/BaseCard.vue
> +				:class="`body--margin-${margin}`"
I added a linter rule, now it will auto-fix, thanks

2022-09-29 05:58 UTC, mateuszRybczonek commented on src/components/BaseTable.vue
> +	sortDesc.value = direction === 'desc'
I agree, `sortDirection` seems more legit than `sortDesc`

2022-09-29 06:40 UTC, mateuszRybczonek commented on src/components/BaseTable.vue
> +	})
I disagree here, I was looking at where it is used in `ui-common-library` and I can't find a single usage.

I see it is used in:
`holofuel-rsm-ui` - 2x `get` / 1x `pick` / 1x `escapeRegExp` occurrences
`publisher-portal` - 2x `pick` occurrences
`host-console-ui` - 2x `isFunction` / 1x `isEmpty` (I just replaced them with native JS code and ditched `lodash` from the project)

I think `lodash` is also slowly becoming obsolete, unless we are really doing some crazy data manipulations, but I don't think we are. Most of the things `lodash` gives us can be achieved by using modern JS which is x times faster.

I am not very familiar with `lodash` as I am too young as a developer I guess. I was looking at what lodash is actually giving us and found this https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore, that opened my eyes a bit.

### USE NATIVE JS
I understand why it was used in the past, eg. `pick`, I see that doing that pre ES6 destructuring was madness, but from what I understand all it does is actually destructuring, that can be achieved very easily now.

https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_pick

```
var object = { 'a': 1, 'b': '2', 'c': 3 };

// Underscore/Lodash
var result = _.pick(object, ['a', 'c']);
console.log(result)
// output: {a: 1, c: 3}

// Native (destructuring)
const { a, c } = object;
const result = { a, c};
console.log(result);
// output: {a: 1, c: 3}
// for an array of this object --> array.map(({a, c}) => ({a, c}));

// Native
function pick(object, keys) {
  return keys.reduce((obj, key) => {
     if (object && object.hasOwnProperty(key)) {
        obj[key] = object[key];
     }
     return obj;
   }, {});
}
var result = pick(object, ['a', 'c']);
console.log(result)
// output: {a: 1, c: 3}
```

Back to my `.sort`, I just checked and I can simplify the solution by not checking the `typeof a[sortKey] === 'number'` I think something different was wrong with my data before.

So doing below works fine

```
return itemsCopy.sort((a, b) => {
  if (a[sortKey] === b[sortKey]) {
    return 0
  }

  if (sortDirection.value === ESortDirections.desc) {
    return a[sortKey] > b[sortKey] ? -1 : 1
  } else {
    return a[sortKey] < b[sortKey] ? -1 : 1
  }
})
```

### SUMMARY:
I don't think `lodash` is completely obsolete but I think we should use it only when we can't really find a native solution quickly or it becomes some kind of monster code with a lot of edge cases that need to be covered, then people from `lodash` probably solved it for us.

Also I think we should remove it from `ui-common-library` as it is not used and import it only in projects that really need that.

2022-09-29 20:06 UTC, robbiecarlton approved these changes

2022-09-30 19:46 UTC, merged