Changes to HAppCard for publisher portal hApps view
Holo-Host/ui-common-library pull request #43
Opened 2022-10-24 17:48 UTC by Paterick

This PR makes changes to the shared HAppCard, HAppCardImage, and HAppCardUsasge components to support the hApps view in publisher portal.

Some possible breaking changes to host console ui:

1. Changed the color of the paused status chip. I think I remember C saying that we wanted the colors to match but if not I'll need to change this logic. 
2. I also added published and draft states but this shouldn't affect host console as they are only rendered if the attribute exists.

![image](https://user-images.githubusercontent.com/16830873/197592095-e36c4f75-cf55-4ac2-9184-7f4b23d8bf2e.png)

3.

2022-10-24 18:40 UTC, mateuszRybczonek approved these changes

2022-10-24 18:40 UTC, mateuszRybczonek commented on src/components/HAppCard.vue
> +            :type="EChipType.success"
I think those 3 components should be one with a single `v-if="isStateChipVisible"`

```
const isPaused = computed(() => props.happ.is_paused || props.happ.isPaused)
const isDraft = computed(() => props.happ.is_draft || props.happ.isDraft)

const isStateChipVisible = computed(() => isDraft.value || isPaused.value || props.isPublished
```

and the props to that component should come from another computed property:

```
const stateChipProps = computed(() => {
  if (isPaused.value) {
    return {
      label: '$.paused'
      type: EChipType.danger
  },

  if (isDraft.value) {
    return {....}
  }

  if (props.isPublished) {
   ...
  }
})
```

This way all that logic from the template dissapears:
```
<BaseChip
  v-if="isStateChipVisible"
  :label="$t(stateChipProps.label)"
  :type="stateChipProps.type"
/>
```

2022-10-24 18:40 UTC, mateuszRybczonek commented on src/components/HAppCard.vue
> +            :type="EChipType.danger"
Could you please confirm that color change with @celestialhanley? It might have a different context (importance) for publisher and host.

2022-10-24 21:26 UTC, Paterick commented on src/components/HAppCard.vue
> +            :type="EChipType.danger"
I did talk to C and she did say she wanted the paused hApp chip in host console to stay the color it is now. I updated the PR to distinguish between host console paused and publisher portal paused.

2022-10-24 21:27 UTC, Paterick commented on src/components/HAppCard.vue
> +            :type="EChipType.success"
Great suggestion, I applied it to this PR. Thanks.

2022-10-25 15:31 UTC, mateuszRybczonek requested changes

2022-10-25 15:31 UTC, mateuszRybczonek commented on src/components/HAppCard.vue
> +  if (props.isPublished) {
Actually, I think all that logic should not live in this component. Give me few minutes and I will check if we can use a composable for this. My way of thinking is, "Why should I have "isDraft" and "isPublished" in host console if I don't even have a concept of that in the app?

2022-10-25 16:34 UTC, mateuszRybczonek requested changes

2022-10-25 16:34 UTC, mateuszRybczonek commented on src/components/HAppCard.vue
> +const isDraft = computed(() => props.happ.is_draft || props.happ.isDraft)
Okay, so here's what I suggest, to be able to re-use that component in both apps having totally different chips and states required from the app I suggest using not so well known Vue feature called `provide/inject`.  https://vuejs.org/guide/components/provide-inject.html

What we need to do is:
- remove `isDraft`, `isStateChipVisible` and `stateChipProps` computed props and `isPublished` prop from `HAppCard.vue`.
- add the props we want to inject to this component (`isStateChipVisible`, `stateChipProps`)

```
// HAppCard.vue
...
import ArrowIcon from './icons/ArrowIcon.vue'

const isStateChipVisible = inject('isStateChipVisible')
const stateChipProps = inject('stateChipProps')

const props = defineProps({
// remove isPublished prop from this component, it will be passed using provide/inject
...
```

- create a component in PublisherPortal (or HostConsole) that will use the component from ui-common-library. This component will provide the custom logic that we want to have for each app.

```
// CustomHAppCard.vue
<template>
  <HAppCard
    :key="happ.id"
    :happ="happ"
  />
</template>

<script setup>
import HAppCard from '@uicommon/components/HAppCard.vue'
import { EChipType } from '@uicommon/types/ui'
import { computed, provide } from 'vue'

const props = defineProps({
  happ: {
    type: Object,
    default: () => {}
  }
})

const isPaused = computed(() => props.happ.is_paused)
const isDraft = computed(() => props.happ.is_draft)
const isPublished = computed(() => !props.happ.is_paused && !props.happ.is_draft

const isStateChipVisible = computed(() => isDraft.value || isPaused.value || isPublished.value)

const stateChipProps = computed(() => {
  if (isDraft.value) {
    return {
      label: '$.draft',
      type: EChipType.warning
    }
  }
  if (isPaused.value) {
    return {
      label: '$.paused',
      type: EChipType.danger
    }
  }

  if (isPublished.value) {
   return {
      label: '$.published',
      type: EChipType.success
    }   
  }
}

provide('isStateChipVisible', isStateChipVisible)
provide('stateChipProps', stateChipProps)
</script>
```

- last, instead of using `HAppCard.vue` from the library we use `CustomHAppCard.vue` that we just created.

```
        <CustomHAppCard
          v-for="happ in filteredHapps"
          :key="happ.id"
          :happ="happ"
          class="happs__happ-list-item">

          <template v-slot:link-icon>
            <router-link :to="{ name: 'HappForm', params: { id: happ.id }}" class='arrow-icon'>
              <ArrowIcon />
            </router-link>
          </template>
        </CustomHAppCard>
```

This way we can pass custom logic to a component and reuse the same component in different context. Yay!!!

NOTE: You probably need to move the `<template v-slot:link-icon>` into the `CustomHAppCard.vue` as this is the one using the original `HAppCard.vue` component

2022-10-25 17:04 UTC, robbiecarlton commented on src/components/HAppCard.vue
> +const isDraft = computed(() => props.happ.is_draft || props.happ.isDraft)
The principle makes sense to me. We should pull out logic that's not common into a separate component. I'm not sure we need to use `inject`. What does it get us in this case over just passing `isStateChipVisible` and `stateChipProps` as props?

2022-10-25 17:12 UTC, Paterick commented on src/components/HAppCard.vue
> +const isDraft = computed(() => props.happ.is_draft || props.happ.isDraft)
My other thought was to have the chip component as a slot. I could still use the base chip but pass it into the card vue myself.

2022-10-25 18:02 UTC, mateuszRybczonek commented on src/components/HAppCard.vue
> +const isDraft = computed(() => props.happ.is_draft || props.happ.isDraft)
@robbiecarlton haha, you are right… I think I went into a tunnel, started with a different thought of having custom logic per component but ended up with creating a wrapper component that can take care of some logic and pass two props to it’s child :)

I would call the component in ui-common-library ‘BaseHAppCard.Vue ’ and the one used in the app ‘HAppCard.Vue’ if we want to proceed with this solution.

@Paterick that sounds like an alternative, that way we can have all that logic in a separate (StateChip) component that will be rendered in the slot.

@Paterick I leave the decision to you, both seems to be ok. With a little preference to your slot in my opinion.

2022-10-26 03:08 UTC, Paterick commented on src/components/HAppCard.vue
> +const isDraft = computed(() => props.happ.is_draft || props.happ.isDraft)
Per our conversation, I removed all the publisher portal specific logic, reverted the chip status to its original design, and wrapped it in a slot that the publisher portal uses for its own rendering.

2022-10-26 08:53 UTC, mateuszRybczonek requested changes

2022-10-26 08:53 UTC, mateuszRybczonek commented on src/components/HAppCard.vue
> +            <BaseChip
Could you please remove that BaseChip from here and just leave an empty slot? I don't see a reason why host-console-ui chip should be here and not in the host-console-ui code where the HAppCard is used.

2022-10-26 13:36 UTC, mateuszRybczonek approved these changes
I don't want to block you, I am away for the next few days, so I'll approve this PR. Could you please have a look at my previous comment?

2022-10-26 21:34 UTC, robbiecarlton approved these changes

2022-10-26 22:27 UTC, Paterick commented on src/components/HAppCard.vue
> +            <BaseChip
I removed the default status-chip slot content

2022-10-26 22:28 UTC, merged